//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercePro.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public string title { get; set; }
        public string notes { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public System.DateTime date { get; set; }
        public int order_id { get; set; }
        public int status { get; set; }
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
