//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercePro.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int id { get; set; }
        public string title { get; set; }
        public string notes { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public System.DateTime date { get; set; }
        public int product_id { get; set; }
        public int durum { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
