//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommercePro.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string companyName { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string adress { get; set; }
        public Nullable<int> fax { get; set; }
        public string email { get; set; }
        public string url { get; set; }
        public string paymentType { get; set; }
        public string DiscountType { get; set; }
        public string notes { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
